export const ACTION_TYPES = {
  inputChanged: "input.changed",
  mouseClick: "mouse.click",
  mouseDown: "mouse.down",
  mouseUp: "mouse.up",
  mouseOver: "mouse.over",
  mouseOut: "mouse.out",
  mouseMove: "mouse.move",
  mouseDblClick: "mouse.dblclick",
  mouseContextMenu: "mouse.contextmenu",
  mouseEnterLeave: "mouse.enterleave",
  pointer: "pointer.action",
  focus: "element.focus",
  formSubmit: "form.submit",
  formReset: "form.reset",
  keyboardKey: "keyboard.key",
  composition: "composition.action",
  textSelect: "text.select",
  scroll: "viewport.scroll",
  clipboard: "clipboard.action",
  touch: "touch.action",
  drag: "drag.action",
  wheel: "viewport.wheel",
  navigation: "page.navigation",
} as const;
